import type { Dictionary } from "./ru";

export const en: Dictionary = {
  meta: {
    title: "Fitting Room — virtual try-on from a photo",
    description:
      "Upload your photo, pick a garment, and see how it looks on you. Results in seconds, no sign-up required.",
  },

  nav: {
    how: "How it works",
    faq: "FAQ",
    tryOn: "Try it on",
    skipToContent: "Skip to content",
  },

  hero: {
    badge: "AI-powered try-on",
    titleLine1: "Try clothes on",
    titleLine2: "without leaving home",
    subtitle:
      "Upload your photo, choose a garment, and see how it looks on you within seconds. No sign-up, no queue for the fitting room.",
    ctaPrimary: "Try it free",
    ctaSecondary: "How it works",
    stat1: "seconds per try-on",
    stat2: "items in the catalog",
    stat3: "photos stored",
    stat3Value: "0 files",
  },

  studio: {
    title: "Fitting room",
    subtitle: "Three steps, then download the result.",
    stepLabel: "Step",

    person: {
      title: "Your photo",
      label: "Photo of a person",
      hint: "Works best: full-length or waist-up, facing the camera, light background.",
      empty: "Click or drop a photo here",
      processing: "Processing…",
      remove: "Remove",
      change: "Replace",
      tipsTitle: "What makes a good photo",
      tip1: "Full-length or waist-up",
      tip2: "Facing the camera, arms relaxed",
      tip3: "Plain, light background",
      tip4: "Even light, no harsh shadows",
    },

    garment: {
      title: "Garment",
      tabCatalog: "From catalog",
      tabUpload: "Your own photo",
      label: "Photo of the garment",
      hint: "The whole item on a plain background, like a product shot.",
      categoryLabel: "Garment type",
      filterAll: "All",
    },

    result: {
      title: "Result",
      empty: "Your try-on will appear here",
      emptyHint: "Upload a photo and pick a garment",
      loading: "Trying it on…",
      loadingHint: "Usually takes 10–30 seconds",
      elapsed: "{seconds}s elapsed",
      download: "Download result",
      retry: "Try again",
      tryAnother: "Try another item",
      doneIn: "Done in {seconds}s",
      demoNote: "Demo mode: the AI model is not connected.",
      compareHint: "Drag to compare",
      before: "Before",
      after: "After",
    },

    submit: "Try it on",
    submitting: "Trying it on…",
    needPerson: "Upload your photo first.",
    needGarment: "Pick an item from the catalog or upload your own photo.",
    demoBanner:
      "Demo mode: the AI model is not connected, so the result is a watermarked placeholder.",
  },

  categories: {
    auto: "Detect automatically",
    tops: "Tops",
    bottoms: "Bottoms",
    "one-pieces": "Dresses",
  },

  categoryHints: {
    tops: "T-shirts, shirts, hoodies",
    bottoms: "Jeans, skirts, shorts",
    "one-pieces": "Dresses and jumpsuits",
  },

  how: {
    title: "How it works",
    subtitle: "Nothing to install — everything happens in your browser.",
    step1Title: "Upload your photo",
    step1Text: "An ordinary full-length or waist-up shot will do. The main thing is that you face the camera.",
    step2Title: "Choose a garment",
    step2Text: "Pick one from the catalog or upload a photo of your own — a product shot from a store works well.",
    step3Title: "Get the result",
    step3Text: "Within seconds you will see yourself in the chosen item. Download it or compare it with the original.",
  },

  faq: {
    title: "Frequently asked questions",
    q1: "What happens to my photos?",
    a1: "Photos are not stored: nothing is written to disk, to a database or to logs. Your photo lives in memory only during the try-on and is gone as soon as the response is sent. During generation it is passed to the AI provider — without that, a try-on is technically impossible.",
    q2: "How accurate is the result?",
    a2: "It is a visualisation, not an exact copy of the garment on you. Front-facing shots in a relaxed pose work best. Unusual poses, very loose clothing and small lettering on fabric can come out distorted.",
    q3: "Do I need an account?",
    a3: "No. The try-on works straight away — no account, no payment.",
    q4: "Which garment photo should I upload?",
    a4: "The whole item on a plain background works best, like a product shot in an online store. A photo on a model works too.",
    q5: "Why did the try-on fail?",
    a5: "Usually it is the source photo: the person stands sideways, part of the body is cut off, or the shot is too dark. Another photo normally fixes it.",
  },

  footer: {
    disclaimer:
      "The result is generated by AI and is an approximate visualisation: fit, small details and prints may differ from the real garment.",
    privacy: "Photos are not stored on the server",
    photos: "Catalog photos — Unsplash",
    rights: "Demonstration project",
  },

  errors: {
    PERSON_MISSING: "Upload a photo of a person.",
    PERSON_FORMAT: "Photo of a person: unsupported format. Use JPEG, PNG or WebP.",
    PERSON_TOO_LARGE: "The photo of the person is too large. Maximum {maxMb} MB.",
    GARMENT_MISSING: "Pick a garment or upload its photo.",
    GARMENT_FORMAT: "Garment photo: unsupported format. Use JPEG, PNG or WebP.",
    GARMENT_TOO_LARGE: "The garment photo is too large. Maximum {maxMb} MB.",
    CATALOG_NOT_FOUND: "That catalog item was not found. Please refresh the page.",
    RATE_LIMITED: "Too many try-ons in a row. Please wait {seconds}s.",
    MODERATION: "The photo did not pass moderation. Please upload an ordinary clothed photo.",
    NO_PERSON: "No person could be detected in the photo. Use a front-facing shot with the body in frame.",
    BAD_IMAGE: "The image could not be processed. Please try another photo.",
    NOT_CONFIGURED: "The try-on service is not configured. Please contact the administrator.",
    NO_CREDITS: "Generation credits have run out. Please contact the administrator.",
    TIMEOUT: "Generation took too long. Please try again.",
    EMPTY_RESULT: "The model returned an empty result. Please try again.",
    UNAVAILABLE: "The try-on service is temporarily unavailable. Please try later.",
    NETWORK: "No connection to the server. Check your internet and try again.",
    FILE_NOT_IMAGE: "That is not an image. Upload a JPEG, PNG or WebP file.",
    FILE_TOO_LARGE: "The file is too large ({sizeMb} MB). Maximum {maxMb} MB.",
    FILE_UNREADABLE: "This photo could not be opened. Save it as JPEG and try again.",
    UNKNOWN: "The try-on could not be completed. Please try again.",
  },

  items: {
    "tee-white": "White T-shirt",
    "tee-black": "Black T-shirt",
    "tee-stripe": "Striped T-shirt",
    "shirt-denim": "Denim shirt",
    "shirt-floral": "Floral shirt",
    "sweatshirt-grey": "Grey sweatshirt",
    "hoodie-print": "Printed hoodie",
    "sweater-white": "White sweater",
    "jacket-denim": "Denim jacket",
    "top-slip-black": "Black slip top",
    "jeans-blue": "Blue jeans",
    "jeans-black": "Black jeans",
    "shorts-beige": "Beige shorts",
    "skirt-black": "Black skirt",
    "dress-terracotta": "Terracotta dress",
  },

  lang: {
    label: "Language",
    change: "Change language",
  },
};
